apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlNtOTFTbTk1TnpjNloybDBhSFZpWDNCaGRGOHhNVUUxV1ZaVVRra3dNVFY1Umxob1ptNXRORW94WDNCUE1VSXhWWE5JVEZSNE9FWkZlbXN6V2pGNFZrMHlUR3RGWlVkTE0wUmlTWGN3VkVoU2JIbDVhRk5MVmsxS1MxazFTVGg1TkdaWk1YTnQiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
